#!/bin/sh
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# Invoke the "rush prettier" custom command to reformat files whenever they
# are committed.
node common/scripts/install-run-rush.js prettier || exit $?

# Invoke the "rush lint-staged-hook" custom command to lint code quality errors on
# files whenever they are committed.
node common/scripts/install-run-rush.js lint-staged-hook || exit $?
